DATASET:
  DATASET_DIRECTORY : '/pscratch/sd/z/zhantao/neurorient_repo/data'
  PDB               : 1BXR
  POISSON           : true
  INCREASE_FACTOR   : 10
  NUM_IMG           : 10000
  FRAC_TRAIN        : 0.9
  BATCH_SIZE        : 40
  NUM_WORKERS       : 10
  USES_RANDOM_PATCH : false


MODEL:
  OVERSAMPLING    : 1.
  BACKBONE:
    RES_TYPE      : 18
    PRETRAIN      : true
  USE_BIFPN       : false


OPTIM:
  LR              : 3e-4
  WEIGHT_DECAY    : 1e-4
  LOSS_FUNC       : 'MSELoss'
  SCHEDULER: 
    NAME          : 'CosineLRScheduler'
    WARMUP_EPOCHS : 5
    TOTAL_EPOCHS  : 1000
    MIN_LR        : 1e-7


TRAINING:
  SEED                  : 42
  CHKPT_DIRECTORY       : chkpts
  MAX_EPOCHS            : 1000
  NUM_GPUS              : 4
  BASE_DIRECTORY        : "/pscratch/sd/z/zhantao/neurorient_repo"