CHKPT:
  DIRECTORY           : chkpts
  FILENAME_PREFIX     : null
  PATH_CHKPT_PREV     : null
  CHKPT_SAVING_PERIOD : 5
  EPOCH_UNSTABLE_END  : 40

DATASET:
  PDB               : 1BXR
  POISSON           : true
  INCREASE_FACTOR   : 10
  NUM_IMG           : 10000
  FRAC_TRAIN        : 1.0
  BATCH_SIZE        : 40
  NUM_WORKERS       : 10
  USES_RANDOM_PATCH : false

IMG_METADATA:
  H : 4
  W : 4

MODEL:
  BIFPN:
    NUM_BLOCKS   : 3
    NUM_FEATURES : 64
    NUM_LEVELS   : 3
  FREEZES_BACKBONE       : false
  USES_RANDOM_WEIGHTS    : false
  RESNET50_OUT_FEATURES  : 32768
  RESNET50_FEATURE_LAYER : -1
  HEAD:
    ANCHOR_LAYER : -1

LOSS:
  SCALE_FACTOR : 10

OPTIM:
  LR           : 3e-4
  WEIGHT_DECAY : 1e-4
  GRAD_CLIP    : 1.0

LR_SCHEDULER:
  PATIENCE      : 10
  WARMUP_EPOCHS : 5
  TOTAL_EPOCHS  : 500
  MIN_LR        : 1e-7
  USES_PREV     : true

DDP:
  BACKEND                : nccl
  USES_UNIQUE_WORLD_SEED : false

LOGGING:
  DIRECTORY       : logs
  FILENAME_PREFIX : null

MISC:
  USES_MIXED_PRECISION : false
  MAX_EPOCHS           : 1000
  NUM_GPUS             : 2

HISTORY:
  PREV : null
