from pytorch3d.transforms import matrix_to_quaternion, quaternion_to_matrix
import torch
from pytorch3d.transforms import so3_log_map, so3_exp_map

def compute_weighted_average_so3(rotmats, weights):
    """
    rotmats of shape (B, N, 3, 3)
    weights of shape (B, N,)
    """
    if rotmats.ndim == 3:
        rotmats = rotmats.unsqueeze(0)
    if weights.ndim == 1:
        weights = weights.unsqueeze(0)
    weights = weights / weights.sum(dim=-1, keepdim=True)
    quats = matrix_to_quaternion(rotmats)
    quats_weighted = (quats * weights.unsqueeze(-1)).sum(dim=1)
    quats_weighted = quats_weighted / quats_weighted.norm(dim=-1, keepdim=True)
    return quaternion_to_matrix(quats_weighted)


def compute_weighted_average_karcher_so3(
    Rs: torch.Tensor,      # (B, N, 3, 3) rotation matrices
    weights: torch.Tensor, # (B, N) weights, nonnegative
    max_iter: int = 10,
    tol: float = 1e-7
) -> torch.Tensor:
    """
    Modified from the draft generated by GPT-o1

    Compute the Karcher mean (intrinsic mean) of rotation matrices using
    an iterative log-exp approach, for each batch separately.

    Args:
        Rs: (B, N, 3, 3) batch of rotation matrices
        weights: (B, N) weights per rotation (assumed to sum to 1 along dim=1, 
                 but not strictly necessary—only relative weights matter)
        max_iter: Maximum number of iterations
        tol: Convergence tolerance based on the update size in tangent space

    Returns:
        Rmean: (B, 3, 3) intrinsic mean rotation for each batch
    """

    if Rs.ndim == 3:
        Rs = Rs.unsqueeze(0)
    if weights.ndim == 1:
        weights = weights.unsqueeze(0)
    
    pre_shape = Rs.shape[:2]
    print(pre_shape)

    device = Rs.device
    B, N, _, _ = Rs.shape

    # Normalize weights along dim=1 (optional but often helpful).
    # This ensures sum of weights = 1 for each batch.
    w_sums = torch.clamp(weights.sum(dim=1, keepdim=True), min=1e-9)
    w = weights / w_sums

    # Start with the identity as an initial estimate.
    # shape: (B, 3, 3) broadcast identity
    Rmean = torch.eye(3, device=device).unsqueeze(0).expand(B, 3, 3).clone()

    for _ in range(max_iter):
        # Compute Rmean^T * R_i for each i:
        # shape: (B, N, 3, 3)
        Rmean_inv = Rmean.transpose(-2, -1)  # since Rmean is orthonormal
        Rmean_inv_Ri = torch.matmul(Rmean_inv.unsqueeze(1), Rs)

        # Log map on each Rmean_inv_Ri to get tangent vectors in so(3).
        # so3_log_map returns a (B, N, 3) vector of axis-angle parameters.
        log_vecs = so3_log_map(Rmean_inv_Ri.view(-1,3,3)).view(pre_shape + (3,))  # (B, N, 3)

        # Weighted sum in the tangent space (B, 3).
        update_vec = torch.sum(log_vecs * w.unsqueeze(-1), dim=1)

        # If the update is very small, we are close to convergence.
        # A robust check is the norm of the update vector itself.
        update_norm = update_vec.norm(dim=1).mean()  # average over B
        if update_norm < tol:
            break

        # Exponentiate to get the incremental rotation (B, 3, 3).
        update_rot = so3_exp_map(update_vec.view(-1,3)).view((B,3,3))  # shape: (B, 3, 3)

        # Update the mean estimate: Rmean <- Rmean * update_rot
        Rmean = torch.matmul(Rmean, update_rot)

    return Rmean


def karcher_mean_so3_single_cluster(
    Rs: torch.Tensor, 
    weights: torch.Tensor,
    max_iter: int = 10,
    tol: float = 1e-7
) -> torch.Tensor:
    """
    Compute the weighted Karcher mean (intrinsic mean) of the rotation
    matrices in `Rs`, for a single cluster (N, 3, 3).
    """
    device = Rs.device
    N = Rs.shape[0]

    # Normalize weights so sum of weights = 1 (optional, but often helpful).
    w_sum = torch.clamp(weights.sum(), min=1e-9)
    w = weights / w_sum

    # Start with identity as initial guess.
    Rmean = torch.eye(3, device=device).clone()  # (3, 3)

    for _ in range(max_iter):
        Rmean_inv = Rmean.transpose(0, 1)  # Rmean^T
        # (N, 3, 3): each R_i -> Rmean^T * R_i
        Rmean_inv_Ri = torch.matmul(Rmean_inv.unsqueeze(0), Rs)

        # so3_log_map => (N, 3)
        log_vecs = so3_log_map(Rmean_inv_Ri)

        # Weighted sum of tangent vectors => (3,)
        update_vec = torch.sum(log_vecs * w.unsqueeze(-1), dim=0, keepdim=True)

        # Check update size for convergence
        update_norm = torch.linalg.norm(update_vec)
        if update_norm < tol:
            break

        # Exponentiate in so(3)
        update_rot = so3_exp_map(update_vec)  # (3, 3)

        # Rmean <- Rmean * update_rot
        Rmean = torch.matmul(Rmean, update_rot).squeeze(0)

    return Rmean


def so3_kmeans(
    Rs: torch.Tensor, 
    weights: torch.Tensor, 
    K: int, 
    max_iter: int = 10,
    tol: float = 1e-5,
    karcher_max_iter: int = 10
):
    """
    Perform k-means style clustering on rotation matrices in SO(3) using
    the geodesic distance. Return:
      - cluster_labels: (N,) assignment of each R_i to a cluster in [0..K-1]
      - cluster_centers: (K, 3, 3) the final cluster centers
      - cluster_weights: (K,) the total weight assigned to each cluster

    Args:
        Rs: (N, 3, 3) rotation matrices
        weights: (N,) per-rotation weights
        K: number of clusters
        max_iter: max number of k-means iterations
        tol: stop if cluster assignments stop changing significantly
        karcher_max_iter: max iteration for computing each cluster's Karcher mean
    """
    device = Rs.device
    N = Rs.shape[0]

    # 1) Initialize cluster centers by randomly picking K distinct rotations
    #    (or you could do something more sophisticated like k-means++ style).
    #    We'll keep it simple here.
    indices = torch.randperm(N, device=device)[:K]
    cluster_centers = Rs[indices]  # (K, 3, 3)

    # We'll store the cluster assignment for each rotation
    cluster_labels = torch.zeros(N, dtype=torch.long, device=device)

    for iter_i in range(max_iter):
        # --- Assignment step ---
        # For each R_i, we compute distance to each cluster center => pick min
        # distance = || log( center^T * R_i ) || in R^3
        # We'll do this in a loop or a chunked manner for clarity.

        # cluster_distances: (N, K)
        cluster_distances = []
        for k in range(K):
            ck_inv = cluster_centers[k].transpose(0, 1)  # (3, 3)
            # (N, 3, 3)
            ck_inv_Ri = torch.matmul(ck_inv.unsqueeze(0), Rs)
            # (N, 3)
            log_vecs = so3_log_map(ck_inv_Ri)
            # Distances are the L2 norm in R^3
            dists = torch.linalg.norm(log_vecs, dim=1)
            cluster_distances.append(dists)
        cluster_distances = torch.stack(cluster_distances, dim=1)  # (N, K)

        # Argmin across K for each R_i
        new_labels = torch.argmin(cluster_distances, dim=1)

        # Check how many changed
        diff = (new_labels != cluster_labels).sum().item()
        cluster_labels = new_labels

        # --- Update step ---
        # For each cluster, gather its members (and weights) and compute the
        # Karcher mean. If a cluster has no members, we can skip or re-init.

        new_centers = []
        for k in range(K):
            # mask for cluster k
            members = (cluster_labels == k)
            if not torch.any(members):
                # no members? re-init from a random R
                idx = torch.randint(0, N, (1,), device=device)
                new_centers.append(Rs[idx].squeeze(0))
            else:
                # gather rotations & weights
                Rk = Rs[members]         # shape: (#members, 3, 3)
                wk = weights[members]    # shape: (#members,)
                # compute Karcher mean of that cluster
                c_k = karcher_mean_so3_single_cluster(
                    Rk, wk, max_iter=karcher_max_iter
                )
                new_centers.append(c_k)
        cluster_centers = torch.stack(new_centers, dim=0)  # (K, 3, 3)

        # If fewer than say 1% changed, consider we're done
        if diff < 0.01 * N:
            break

    # Compute total weights per cluster
    cluster_weights = torch.zeros(K, device=device)
    for k in range(K):
        cluster_weights[k] = weights[cluster_labels == k].sum()

    return cluster_labels, cluster_centers, cluster_weights


def pick_largest_weight_cluster(
    cluster_labels: torch.Tensor,
    cluster_centers: torch.Tensor,
    cluster_weights: torch.Tensor
):
    """
    Given the results of so3_kmeans, pick the cluster with the heaviest total weight.
    Return the cluster index and the cluster center.
    """
    best_cluster = torch.argmax(cluster_weights).item()
    best_center = cluster_centers[best_cluster]  # (3, 3)
    return best_cluster, best_center